# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json

id: "test-project-3"
thumbnail: "https://qaforce.co.uk/wp-content/uploads/2018/01/93df749e28b1d2b1068013fc484f6407-nfl-memes-san-francisco-ers.jpg"
image: "https://s3.timeweb.com/132514fc-images-staging/content/lautaro-andreani-UYsBCu9RP3Y-unsplash.jpg"
title: "Test project 3"
shortDescription: |
  consectetur adipiscing elit. Nunc facilisis turpis vitae
  sollicitudin interdum. Quisque nibh nibh, semper ut libero id,
description: |
  *super puper description project*
cases:
  - "test-case"
