# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json
id: "test-project-3"
thumbnail: "https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/28147d49c5164610be2e586dbaa53e91.gif"
image: "https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/28147d49c5164610be2e586dbaa53e91.gif"
name: "Покупка товара"
description: |
  *Project the best description*
shortDescription: Lorem ipsum dolor sit amet,
  consectetur adipiscing elit. Nunc facilisis turpis vitae
  sollicitudin interdum. Quisque nibh nibh, semper ut libero id,
cases:
  - "case-1"
product:
  access: private