# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json
id: "test-project-2"
thumbnail: "https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/New-Hire-Form-Cover.webp"
image: "https://s3.timeweb.com/132514fc-images-staging/content/lautaro-andreani-UYsBCu9RP3Y-unsplash.jpg"
title: "Пройти ознакомительный этапe"
description: |
  *test the best description*

shortDescription:
  Подробно заполните свой профиль

  Заполнить поля
  
  - [x] Write the press release
  - [ ] Update the website
  - [ ] Contact the media


dependencies:
  - "test-project-3"
cases:
  - "test-case"
