# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json

id: "clzfm0m6k000a089a7l88de4f"
thumbnail: "https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/logo-react.svg"
image: "https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/images.jpeg"
title: "Test project 242 !!!111"
shortDescription: "short description example"
description: |
  *Project the best 123*
  
  ![some text](https://s3.timeweb.cloud/ca1c67e1-tcms-images/content/images.jpeg)
  
  > цитата
  
  
  ```html
    <div>123</div>
  ```
  
  - 1. Пункт первый
  - 2. Пункт второй
  - 3. [Пункт третий](https://google.com)

  ### Заголовок два

  тест текст 123!!!
cases:
  - "case-1"