# yaml-language-server: $schema=https://raw.githubusercontent.com/yurifyodorov/tcms-content-schema/main/schemas/project.schema.json
id: "test-project-1"
thumbnail: "https://uploads.sitepoint.com/wp-content/uploads/2017/04/1493235373large_react_apps_A-01.png"
image: "https://s3.timeweb.com/132514fc-images-staging/content/lautaro-andreani-UYsBCu9RP3Y-unsplash.jpg"
title: "Подготовка к тестированию"
description: |

  В sefefes sefesf esf:
  - sefefss
  - sefefs
  - efsfes
  - refesfse

shortDescription: |

  В sefefes sefesf esf:
  - sefefss
  - sefefs
  - efsfes
  - refesfse


dependencies:
  - "test-project-2"
cases:
  - "case-1"
  - "case-2"
  - "case-3"
